import React from 'react';

const hermits = [
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "bdoubleo100",
    "DisplayName": "BDoubleO",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-jdIst1b1IE24PWbjjN8WijYLwb62YDv9k3A=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "BdoubleO100",
    "TwitchName": "bdoubleo",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UClu2e7S8atp6tG2galK9hgg",
    "UploadPlaylistID": "UUlu2e7S8atp6tG2galK9hgg",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "cubfan135",
    "DisplayName": "cubfan135",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-BJGa9Okc3w5jwu5OeW1spe_FY2VC7TMDm0Q=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "cubfan135",
    "TwitchName": "cubfan135",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UC9lJXqw4QZw-HWaZH6sN-xw",
    "UploadPlaylistID": "UU9lJXqw4QZw-HWaZH6sN-xw",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "docm77",
    "DisplayName": "Docm77",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-gjLPd9nARXXk7R9IKOS9AtYt68nbixboTIg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "docm77",
    "TwitchName": "docm77live",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UC4O9HKe9Jt5yAhKuNv3LXpQ",
    "UploadPlaylistID": "UU4O9HKe9Jt5yAhKuNv3LXpQ",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "ethoslab",
    "DisplayName": "Etho",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a-/AAuE7mA-ZIagIpZkOlXv2OhgQQDxsi3MkBBVm3KaoA=s288-mo-c-c0xffffffff-rj-k-no",
    "TwitterName": "EthoLP",
    "TwitchName": "ethotv",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCFKDEp9si4RmHFWJW1vYsMA",
    "UploadPlaylistID": "UUFKDEp9si4RmHFWJW1vYsMA",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "falsesymmetry",
    "DisplayName": "False",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-9_GWX940aWKZb80fbN55eGr3k-HmjsZ2ycg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "falsesymmetry",
    "TwitchName": "FalseSymmetry",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCuQYHhF6on6EXXO-_i_ClHQ",
    "UploadPlaylistID": "UUuQYHhF6on6EXXO-_i_ClHQ",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "xelqua",
    "DisplayName": "Grian",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_PNNZHfKhyL6ytQRRD-_jq_eQDReiz5dXuRQ=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "GrianMC",
    "TwitchName": "grianmc",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCR9Gcq0CMm6YgTzsDxAxjOQ",
    "UploadPlaylistID": "UUR9Gcq0CMm6YgTzsDxAxjOQ",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "hypnotizd",
    "DisplayName": "Hypno",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-0tOo5kPdPHL2rUXQrwAIurlFBAPpsHwlo6A=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "hypnotizd_",
    "TwitchName": "hypnotizd",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UChi5MyXJLQuPni3dM19Ar3g",
    "UploadPlaylistID": "UUhi5MyXJLQuPni3dM19Ar3g",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "impulsesv",
    "DisplayName": "impulseSV",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-4CGaLx7vB6_zpGA_g2muX-7dpi6nu8klPYg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "impulseSV",
    "TwitchName": "impulsesv",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCuMJPFqazQI4SofSFEd-5zA",
    "UploadPlaylistID": "UUuMJPFqazQI4SofSFEd-5zA",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "iskall85",
    "DisplayName": "iskall85",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l799PkbxiHI5EXQnVKgZXYIcePtJMQUQwDAIJg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "iskall85",
    "TwitchName": "iskall85",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCZ9x-z3iOnIbJxVpm1rsu2A",
    "UploadPlaylistID": "UUZ9x-z3iOnIbJxVpm1rsu2A",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "ijevin",
    "DisplayName": "Jevin",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-oMxAYPKmqk6SAPTypYcShe_e1rlHuWb0C1g=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "ijevin",
    "TwitchName": "ijevin",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCrEtZMErQXaSYy_JDGoU5Qw",
    "UploadPlaylistID": "UUrEtZMErQXaSYy_JDGoU5Qw",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "joehillstsd",
    "DisplayName": "joehills",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l788Cy63rOXC8AAibKFOQBJJqUzSO9CtJyDi8A=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "joehills",
    "TwitchName": "joehills",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCtWObtiLCNI_BTBHwEOZNqg",
    "UploadPlaylistID": "UUtWObtiLCNI_BTBHwEOZNqg",
    "balance": 0,
    "savings": 0
  },
  {
    "id": 0,
    "BeamName": "",
    "ChannelName": "keralis",
    "DisplayName": "Keralis",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l78CmC8owyrUVl0oia0tnvcYi5RZVAmpsopohg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "worldofkeralis",
    "TwitchName": "keralis",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCcJgOennb0II4a_qi9OMkRA",
    "UploadPlaylistID": "UUcJgOennb0II4a_qi9OMkRA",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "thatmumbojumbo",
    "BeamName": "",
    "ChannelName": "thatmumbojumbo",
    "DisplayName": "MumboJumbo",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_nKzN_UILeQrGZpqtxpGGCG0E0QPD7Bz8xQw=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "ThatMumboJumbo",
    "TwitchName": "thatmumbojumbo",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UChFur_NwVSbUozOcF_F2kMg",
    "UploadPlaylistID": "UUhFur_NwVSbUozOcF_F2kMg",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "rendog",
    "BeamName": "",
    "ChannelName": "rendog",
    "DisplayName": "rendog",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_Lkg0zuSa_nslliXBX9OsYpJWNr5ZPX6qOow=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "renthedog",
    "TwitchName": "rendogtv",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCDpdtiUfcdUCzokpRWORRqA",
    "UploadPlaylistID": "UUDpdtiUfcdUCzokpRWORRqA",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "goodtimeswithscar",
    "BeamName": "",
    "ChannelName": "goodtimeswithscar",
    "DisplayName": "Scar",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_vWxwRlTJcu7PVKvyJOs-CTBFTl8h1aVhugg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "GTWScar",
    "TwitchName": "goodtimeswithscar",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCodkNmk9oWRTIYZdr_HuSlg",
    "UploadPlaylistID": "UUodkNmk9oWRTIYZdr_HuSlg",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "stressmonster",
    "BeamName": "",
    "ChannelName": "stressmonster101",
    "DisplayName": "Stress",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_1rcAfcbvOFHZ1Btf2FlarPnNz5I7L_uznrA=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "Stressmonsterin",
    "TwitchName": "stressmonster",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UC24lkOxZYna9nlXYBcJ9B8Q",
    "UploadPlaylistID": "UU24lkOxZYna9nlXYBcJ9B8Q",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "tangotek",
    "BeamName": "",
    "ChannelName": "tangoteklp",
    "DisplayName": "Tango Tek",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_5OYrRsQTenvmtdPs5iHZI8_HhkaAP5NljsQ=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "TangoTekLP",
    "TwitchName": "tangotek",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UC4YUKOBld2PoOLzk0YZ80lw",
    "UploadPlaylistID": "UU4YUKOBld2PoOLzk0YZ80lw",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "tinfoilchef",
    "BeamName": "",
    "ChannelName": "selif1",
    "DisplayName": "TinfoilChef",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-bwUwP8Zz40snodYPv1GTQgj7pUp_o4_zSEQ=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "tinfoilchef",
    "TwitchName": "tinfoilchef",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCRatys97ggrXVtQQBGRALkg",
    "UploadPlaylistID": "UURatys97ggrXVtQQBGRALkg",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "vintagebeef",
    "BeamName": "",
    "ChannelName": "vintagebeef",
    "DisplayName": "Vintage Beef",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l78UY9UkrkIuUS9LIg17n1fhKSIayjsugWMsTw=s288-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "vintagebeeflp",
    "TwitchName": "VintageBeef",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCu17Sme-KE87ca9OTzP0p7g",
    "UploadPlaylistID": "UUu17Sme-KE87ca9OTzP0p7g",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "welsknight",
    "BeamName": "",
    "ChannelName": "welsknightgaming",
    "DisplayName": "Welsknight",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l793n0C0S0dg14vaPV265WJffsetWrUGfUIjVA=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "welsknightplays",
    "TwitchName": "welsknight",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCKEJZ-dqIA03evnzEy1_owg",
    "UploadPlaylistID": "UUKEJZ-dqIA03evnzEy1_owg",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "xbcrafted",
    "BeamName": "",
    "ChannelName": "xbxaxcx",
    "DisplayName": "xBCrafted",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-yCXpYvoqNghtNNXdgCVKecKgA9SUnxPAgOw=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "xBCrafted",
    "TwitchName": "xbcrafted",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UC_MkjhQr_D_lGlO3uu-GxyA",
    "UploadPlaylistID": "UU_MkjhQr_D_lGlO3uu-GxyA",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "xisumavoid",
    "BeamName": "",
    "ChannelName": "xisumavoid",
    "DisplayName": "Xisuma",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l78q19X29K_HCXvPrJ_X4uyqEElUKvR97itnZg=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "xisumavoid",
    "TwitchName": "xisuma",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCU9pX8hKcrx06XfOB-VQLdw",
    "UploadPlaylistID": "UUU9pX8hKcrx06XfOB-VQLdw",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "zedaphplays",
    "BeamName": "",
    "ChannelName": "zedaphplays",
    "DisplayName": "ZedaphPlays",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7-E32aR58QJ8arDv7464ZomvJfIH4OLd4Wumw=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "ZedaphPlays",
    "TwitchName": "ZedaphPlays",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCPK5G4jeoVEbUp5crKJl6CQ",
    "UploadPlaylistID": "UUPK5G4jeoVEbUp5crKJl6CQ",
    "balance": 0,
    "savings": 0
  },
  {
    "id": "zombiecleo",
    "BeamName": "",
    "ChannelName": "zombiecleo",
    "DisplayName": "ZombieCleo",
    "GooglePlusLink": "",
    "ProfilePicture": "https://yt3.ggpht.com/a/AGF-l7_SPPaYuaxChEgGG_SEQmiym3WTEukF6A_Z1A=s88-c-k-c0xffffffff-no-rj-mo",
    "TwitterName": "ZombieCleo",
    "TwitchName": "zombiecleo",
    "WebsiteURL": "",
    "Active": true,
    "Streaming": false,
    "BeamStreaming": false,
    "YTStreaming": false,
    "ChannelID": "UCjI5qxhtyv3srhWr60HemRw",
    "UploadPlaylistID": "UUjI5qxhtyv3srhWr60HemRw",
    "balance": 0,
    "savings": 0
  }
];

const useHermits = () => {
  return hermits;
}

export default useHermits;

export const useHermit = (name) => {
  return hermits.find(h => h.ChannelName === name);
}
